### ISSUE TITLE
Immutable vs mutable data structures

### ISSUE THREAD

**Issue by greenfork** [cmiles74/bencode#1]
Hi, I really enjoy your library! I have a question about the choice of mutable data structures for representation, why was the decision to choose them instead of immutable ones?

My main use case is that buffers `@"abc"` can't be used in comparisons easily, meaning that `(= @"a" @"a")` prints `false`. This makes it impossible to use in expressions such as `match` and probably others.

I use this function to change everything to immutable structures currently but I wonder if there are any ideas of changing the default one to immutable too:
```janet
(defn deep-immutabilize
  "Turn every mutable structure to immutable one."
  [value]
  (defn immutabilize [v]
    (match (type v)
      :struct (deep-immutabilize v)
      :table (deep-immutabilize v)
      :buffer (string v)
      :array (map immutabilize v)
      :tuple (map immutabilize v)
      _ v))
  (def t (type value))
  (cond
    (or (= :table t) (= :struct t))
    (struct ;(mapcat
              (fn [x]
                (let [first (0 x) second (1 x)]
                  [(keyword first) (deep-immutabilize second)]))
              (pairs value)))
    (or (= :array t) (= :tuple t))
    (tuple ;(map deep-immutabilize value))
    (immutabilize value)))
```

**Comment by cmiles74** [comment]
Yes, I agree: having the parser (and the reader) return immutable data objects make the most sense.; we should make returning immutable data structures the default behavior. Since you are the only consumer of this library and you think it's okay, I guess it's just up to the two of us. 😉

My thinking on the mutable bit is that we need to use mutable objects to build up the output anyway (my understanding is that you build up your thing, like a buffer or a list, and when it's done you transform it into the immutable version). Since the code is already there, I think a flag that causes mutable objects to be returned makes sense.

Looking at the code, I believe we need to add the flag for mutable/immutable to the `read-stream` function. From there it will need to be passed to the `read` and the `read-bencode` functions. Once we're in the `read-bencode` function we will want to pass the flag to the three functions that are doing the real work.
- `read-dictionary` - https://github.com/cmiles74/bencode/blob/master/src/bencode.janet#L166
- `read-list` - https://github.com/cmiles74/bencode/blob/master/src/bencode.janet#L151
- `read-string` - https://github.com/cmiles74/bencode/blob/master/src/bencode.janet#L151

Each one creates a mutable data object and uses it to accumulate the data, passing control to one of the other functions as needed (the `read-list` function will pass the reader to the `read-string` function in order to parse a string). At the end of each one of these three functions we can simply check the flag and then return the appropriate data object (turn our buffer into a string or our array into a list, our table into a struct).

What do you think? The changes to the code don't seem too big and it will be a pretty valuable feature.

**Comment by cmiles74** [comment]
This PR looks good to me, thank you!

If you don't have any more changes, I believe you should now be able to click the "Squash and Merge" button in the GitHub UI to finish the process and merge your changes in.

Thanks again for your help. 🙂
